server {
    listen 80;
    listen [::]:80;
    server_name accento.mjalili.com;
    client_max_body_size 25m;
    client_body_timeout 20s;

    location / {
        proxy_pass http://127.0.0.1:8010;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_request_buffering off;
        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
    }
}
